### ISSUE TITLE
[API]:  Implement /drawPixel endpoint

### ISSUE THREAD

**Issue by gabaldon** [otherplane/wittypixels#12]
- Restrictions:
    - x = 0 ⇒ left
    - y = 0 ⇒ top
- Validations:
    - 0 ≥ x < MAX_CANVAS_X - 1
    - 0 ≥ y < MAX_CANVAS_Y - 1
    - Player has enough remaining ink for the specified color.
    - Specified coordinate hasn’t been painted by anyone less than 5 seconds ago.
    - Player didn’t draw in the past 2 seconds

**Comment by guidiaz** [comment]
https://github.com/otherplane/wittypixels/pull/20
