### ISSUE TITLE
(Unconfirmed) Can't redeem $WPX

### ISSUE THREAD

**Issue by aesedepece** [otherplane/wittypixels#129]
At least 2 users are complaining about not being able to redeem $WPX, as the UI shows "invalid token" for them when importing the backup sentence.

On the contrary, a few other users have been able to redeem over the last weekend:
![image](https://user-images.githubusercontent.com/1316439/226561067-0b5751fd-a977-4ee5-8ea8-bd917fb6c60b.png)

https://etherscan.io/address/0x462b572089D3176C1b916AAbe24bC23DE459F5E1

**Comment by Tommytrg** [comment]
The problem with this player was the import link. The copied link was wrong. I was able to generate a new import link with a photo of the badge
