### ISSUE TITLE
[CORE] Define metadata JSON structure

### ISSUE THREAD

**Issue by guidiaz** [otherplane/wittypixels#29]
As to be interpreted by OpenSea.

**Comment by guidiaz** [comment]
https://hackmd.io/cf9bFNF3RtO03kw6Swkx1A

**Comment by aesedepece** [comment]
![image](https://user-images.githubusercontent.com/1316439/216418930-22ab1ed1-c3de-4035-ac0a-b1646c459cd0.png)

**Comment by aesedepece** [comment]
@guidiaz any specs for the "NFT Collection Banner"?

**Comment by aesedepece** [comment]
> @guidiaz any specs for the "NFT Collection Banner"?

@guidiaz ping!

**Comment by aesedepece** [comment]
This is already implemented in #2 and #3
